Book repository
wolox-training/ga-java pull request #4
Opened 2019-11-29 23:52 UTC by hellfishg

## Summary

Create bookRepository interface

## Trello Card

[bookRepositories] https://trello.com/c/4BUejUsw/15-crear-un-repositorio-de-books

2019-12-03 14:23 UTC, jeymarsonwolox requested changes
Excellent!! Just a few comments

2019-12-03 14:23 UTC, jeymarsonwolox commented on src/main/java/wolox/training/repositories/BookRepository.java
> +    Book findByAuthor(String author);
use `Optional<Book>`, in case no book is found by that author

2019-12-03 14:23 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +
add javadoc for this class

2019-12-03 14:23 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +public class Book {
add default constructor, jpa requires it

2019-12-03 14:23 UTC, jeymarsonwolox commented on src/main/java/wolox/training/repositories/BookRepository.java
> +
add javadoc

2019-12-03 14:23 UTC, jeymarsonwolox commented on src/main/java/wolox/training/repositories/BookRepository.java
> +
same

2019-12-04 14:18 UTC, jeymarsonwolox requested changes

2019-12-04 14:18 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +    public Book (){}
move the constructor after the declaration of the variables

2019-12-04 21:11 UTC, jeymarsonwolox approved these changes

2019-12-04 22:55 UTC, IgnOliveto approved these changes
Good Job!!!

2019-12-04 23:07 UTC, merged