Book crud
wolox-training/ga-java pull request #5
Opened 2019-12-02 22:43 UTC by hellfishg

## Summary

Create book CRUD and exceptions

## Trello Card

[trello card] https://trello.com/c/z75Kj68s/18-crear-las-operaciones-crud-de-book

2019-12-03 14:39 UTC, jeymarsonwolox requested changes

2019-12-03 14:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan("wolox.training.models")
this is not necesary

2019-12-03 14:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/controllers/BookController.java
>  public class BookController {
add javadoc

2019-12-03 14:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/exceptions/BookNotFoundException.java
> +@ResponseStatus(code = HttpStatus.NOT_FOUND , reason = "Book Id Mismatch")
add javadoc

2019-12-03 14:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/exceptions/BookAlreadyExistException.java
> +public class BookAlreadyExistException extends RuntimeException {
add javadoc

2019-12-03 14:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/controllers/BookController.java
> +      throw new BookNotFoundException("Book is not found", new Exception());
create `BookIdMismatchException` and use here

2019-12-03 14:39 UTC, jeymarsonwolox commented on src/main/java/wolox/training/controllers/BookController.java
> +    bookRepository.findById(id);
add exception if the book does not exits

2019-12-04 14:20 UTC, jeymarsonwolox requested changes

2019-12-04 14:20 UTC, jeymarsonwolox commented on src/main/java/wolox/training/controllers/BookController.java
> +    bookRepository.findById(id).orElseThrow(() -> new BookIdMismatchException("Book is not found", new Exception()));
use `BookNotFoundException` here

2019-12-04 21:11 UTC, jeymarsonwolox approved these changes

2019-12-04 22:56 UTC, IgnOliveto approved these changes

2019-12-04 23:09 UTC, merged